unit Test.Model.Tarefa3;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Vcl.Forms, ProvaDelphiApp.Model.Interfaces, Data.DB,
  ProvaDelphiApp.Model.Tarefa3, Datasnap.DBClient;

type
  // Test methods for class TModelTarefa3

  TestTModelTarefa3 = class(TTestCase)
  strict private
    FForm: TForm;
    FDataSet: TClientDataSet;
    FModelTarefa3: TModelTarefa3;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomar;
    procedure TestDividir;
  end;

implementation

uses
  System.SysUtils;

procedure TestTModelTarefa3.SetUp;
begin
  FForm := TForm.Create(nil);
  FModelTarefa3 := TModelTarefa3.Create(FForm);
  FDataSet := FModelTarefa3.CriarDataSet.PopularDataSet.GetDataSet;
end;

procedure TestTModelTarefa3.TearDown;
begin
  FDataSet.Free;
  FDataSet := nil;

  FForm.Free;
  FForm := nil;

  FModelTarefa3 := nil;
end;

procedure TestTModelTarefa3.TestSomar;
var
  ReturnValue: Currency;
  ExpectedValue: Currency;
begin
  ExpectedValue := 550.00;

  ReturnValue := StrToFloat(FormatFloat('#0.00', FModelTarefa3.Somar(FDataSet)));

  CheckEquals(ExpectedValue, ReturnValue, 'A função TestSomar falhou.')
end;

procedure TestTModelTarefa3.TestDividir;
var
  ReturnValue: Currency;
  ExpectedValue: Currency;
begin
  ExpectedValue := 11.83;

  ReturnValue := StrToFloat(FormatFloat('#0.00', FModelTarefa3.Dividir(FDataSet)));

  CheckEquals(ExpectedValue, ReturnValue, 'A função TestDividir falhou.')
end;

initialization

RegisterTest(TestTModelTarefa3.Suite);

end.
